controllers:
  resource:
    path: ../src/Controller/
    namespace: App\Controller
  type: attribute
app_commandes:
  path: "/commandes"
  controller: 'App\Controller\CommandesController::index'
recap_commande:
  path: /recapitulatif-commande
  controller: 'App\Controller\CommandesController::recapCommande'
